name: "Check mk agent"
description: "Check mk agent"
version: "1.4.15"
slug: "ha_checkmk_agent"
init: false
startup: services
homeassistant_api: true
host_network: true
full_access: true
ports:
  6556/tcp: 6556
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
